name: Dash CICD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r r.txt

    - name: Run unit tests
      run: |
        pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: DockerHub login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t shreeyxkta/a3-car-price:latest .

    - name: Push Docker Image
      run: docker push shreeyxkta/a3-car-price:latest

    - name: set up config
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/st125168
        chmod 600 ~/.ssh/st125168

        cat << 'EOF' > ~/.ssh/config
        Host bazooka
          HostName bazooka.cs.ait.ac.th
          User st125168
          IdentityFile ~/.ssh/st125168

        Host ml2023
          HostName ml.brain.cs.ait.ac.th
          User st125168
          IdentityFile ~/.ssh/st125168
          ProxyJump bazooka
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        EOF
        chmod 600 ~/.ssh/config

        ssh-keyscan -p 22 -H bazooka.cs.ait.ac.th >> ~/.ssh/known_hosts 2>/dev/null 
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to ml2023
      run: |
        ssh -v st125168@ml2023 << 'EOF'
        cd st125168/
        docker compose down
        docker compose pull 
        docker compose up -d 
        EOF